

const ProductTypes =  {
    ADD_NEW_PRODUCT: ' ADD_NEW_PRODUCT',
    FETCH_PRODUCT:'FETCH_PRODUCT',
    SET_PRODUCT:'SET_PRODUCT',
    DELETE_PRODUCT:'DELETE_PRODUCT',
    FETCH_APRODUCT :'FETCH_APRODUCT',
    SET_APRODUCT : 'SET_APRODUCT'
};

export default ProductTypes
