const ordersTypes={
    SAVE_ORDER_HISTORY:'SAVE_ORDER_HISTORY',
    GET_USER_ORDER_HISTORY:'GET_USER_ORDER_HISTORY',
    SET_USER_ORDER_HISTORY:'SET_USER_ORDER_HISTORY',
    SET_ORDER_DETAILS:'SET_ORDER_DETAILS',
    RESET_ORDER_DETAILS:'RESET_ORDER_DETAILS'

};


export default ordersTypes